/*
=============================================================================
LOAN DEFAULT PREDICTION — COMPLETE DAX LIBRARY (MySQL SYNCED)
=============================================================================
Author  : Ajaya Kumar Pradhan
Target  : loan_default_db (MySQL)
Notes   : Includes Measures and Calculated Columns. Format properties in Power BI to Percentage ('%') instead of multiplying by 100.
=============================================================================
*/

-- ── A. CALCULATED COLUMNS (Add these directly to tables) ───────────────────

-- Add to 'dim_date'
"Month Short" = FORMAT('dim_date'[full_date], "MMM")
"Month Number" = MONTH('dim_date'[full_date])
"Month Initial" = LEFT(FORMAT('dim_date'[full_date], "MMM"), 1)

-- Add to 'dim_customer'
"Income Band" = 
    SWITCH(
        TRUE(),
        'dim_customer'[annual_income] < 30000, "Under 30K",
        'dim_customer'[annual_income] < 60000, "30K-60K",
        'dim_customer'[annual_income] < 100000, "60K-100K",
        "Over 100K"
    )

"Income Band Sort" = 
    SWITCH(
        TRUE(),
        'dim_customer'[annual_income] < 30000, 1,
        'dim_customer'[annual_income] < 60000, 2,
        'dim_customer'[annual_income] < 100000, 3,
        4
    )


-- ── 1. CORE KPIs (Measures) ────────────────────────────────────────────────

"Total Applications" = COUNTROWS('fact_loan')

"Good Loans" = CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[loan_condition] = "Good Loan")

"Bad Loans" = CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[loan_condition] = "Bad Loan")

"Approval Rate %" = DIVIDE([Good Loans], [Total Applications])

"Default Rate %" = DIVIDE([Bad Loans], [Total Applications])

"Total Portfolio £M" = DIVIDE(SUM('fact_loan'[loan_amount]), 1000000)

"Avg Loan Amount" = AVERAGE('fact_loan'[loan_amount])

"Avg Interest Rate" = AVERAGE('fact_loan'[interest_rate])

"Avg DTI" = AVERAGE('fact_loan'[dti])

"Est Interest Income £M" = 
    DIVIDE(
        SUMX(
            'fact_loan', 
            'fact_loan'[loan_amount] * 'fact_loan'[interest_rate] / 100
        ), 
        1000000
    )


-- ── 2. RISK ANALYSIS (Measures) ────────────────────────────────────────────

"Low Risk Loans" = CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[risk_category] = "Low Risk")

"Medium Risk Loans" = CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[risk_category] = "Medium Risk")

"High Risk Loans" = CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[risk_category] = "High Risk")

"High Risk %" = DIVIDE([High Risk Loans], [Total Applications])

"Expected Loss £M" = 
    DIVIDE(
        SUMX(
            'fact_loan', 
            'fact_loan'[loan_amount] * IF('fact_loan'[is_bad_loan] = 1, 1, 0)
        ), 
        1000000
    )

"Risk-Adjusted Net Yield %" = [Avg Interest Rate] - ([Default Rate %] * 0.60)


-- ── 3. AFFORDABILITY & CUSTOMER (Measures) ───────────────────────────────

"Avg Annual Income" = AVERAGE('dim_customer'[annual_income])

"Overextended Borrowers %" = 
    DIVIDE(
        CALCULATE(COUNTROWS('fact_loan'), 'fact_loan'[installment_pct_income] > 30),
        [Total Applications]
    )

"Homeowner %" = 
    DIVIDE(
        CALCULATE(COUNTROWS('dim_customer'), 'dim_customer'[home_ownership] IN {"MORTGAGE", "OWN"}),
        [Total Applications]
    )


-- ── 4. TIME & TRENDING (Measures) ──────────────────────────────────────────

"Default Rate YoY Change" = 
    VAR CurrentRate = [Default Rate %]
    VAR PrevRate    = CALCULATE([Default Rate %], SAMEPERIODLASTYEAR('dim_date'[full_date]))
    RETURN IF(NOT ISBLANK(PrevRate), CurrentRate - PrevRate, BLANK())

"Volume Growth YoY %" = 
    VAR CurrentVol = [Total Applications]
    VAR PrevVol    = CALCULATE([Total Applications], SAMEPERIODLASTYEAR('dim_date'[full_date]))
    RETURN DIVIDE(CurrentVol - PrevVol, PrevVol)


-- ── 5. REGIONAL RANKING (Measures) ─────────────────────────────────────────

"Region Default Rank" = 
    RANKX(
        ALL('dim_property'[region]), 
        [Default Rate %], 
        , 
        DESC, 
        DENSE
    )
